### ISSUE TITLE
Clients receive messages in wrong order

### ISSUE THREAD

**Issue by Pamoi** [dedis/prifi#122]
When many clients are connected (usually 6 or more, with one trustee) one client sometimes receives messages in the wrong order with the following log:

```
E : (                                                         client.NewClient.func2: 110) - Required State INITIALIZING, but in state BEFORE_INIT
2 : (                   client.(*PriFiLibClientInstance).Received_ALL_ALL_PARAMETERS: 104) - Client 1 has been initialized by message.
```

These clients are stuck and do not send their public keys to the relay and prevents the protocol to proceed until a new synchronization is triggered.

**Comment by lbarman** [comment]
Nasty bug solved by our legendary nikkolasg. Fixed 0c30d5c
