### ISSUE TITLE
Ctrl+C does not stop prifi

### ISSUE THREAD

**Issue by Pamoi** [dedis/prifi#123]
This seems to be a consequence of the switch to ONET and makes it very painful to stop prifi.

**Comment by lbarman** [comment]
Seems to be only on Mac, as Italo is also experiencing this, but I'm not. Specifically, you do `./prifi.sh client 0`, but it does not stop ?
@ineiti , do you know anything about that ?

**Comment by Pamoi** [comment]
More details: it happens with every role, I start prifi with `./prifi.sh client 0` for example, and then when I hit ^C the process is not stopped, and logs continue to print in my shell. The only way to stop prifi is to kill the process, moreover it seems the the executable itself (launched by go run) can only be stopped by SIGKILL signals.
To make things even more complicated I am not on Mac but on Debian (unstable).

**Comment by lbarman** [comment]
OK. With nicolas we both use `zsh` instead of `bash`, and it works for us. But the engineers are discussing about a fix for bash ofc

**Comment by nikkolasg** [comment]
Actually, on my machine it works with both bash and zsh. What shell are you running @Pamoi  ? `echo $SHELL` ? and terminal emulator ?

**Comment by ineiti** [comment]
See https://github.com/dedis/onet/pull/98

**Comment by Pamoi** [comment]
My shell is `/bin/bash` and my terminal emulator is `gnome-terminal`. I will try with `zsh` to see if the problem may be caused by `bash`.

**Comment by lbarman** [comment]
Matthieu can you try `Ctrl-Q` or `Ctrl-Z` ? (I really love this way of debugging - "can you try the `I/O` button on your laptop ?")

**Comment by Pamoi** [comment]
`Ctrl-Q`does nothing, `Ctrl-Z` gives me my shell back but the processes (both the script and the prifi binary) are still running.

**Comment by ineiti** [comment]
You can get them away with `killall -9 prifi` or `pkill -9 -f prifi`

**Comment by Pamoi** [comment]
Yes this works (I've been sending the signals from `htop`). The problem happens with `zsh` too on my machine.

**Comment by ineiti** [comment]
@pamoi - `killall` works, or using another shell?

**Comment by ineiti** [comment]
Anyway, try to update with `go get -u github.com/lbarman/prifi/sda/app` and try again

**Comment by Pamoi** [comment]
`killall`, sorry for the confusion.

**Comment by Pamoi** [comment]
The `go get`command gave me an error (`fatal: Not possible to fast-forward, aborting.`) so I manually pulled the `urfave/cli` master branch and it solved the problem !

**Comment by lbarman** [comment]
I added the `-u` inside the `./prifi.sh install` to update all dependencies. Call `./prifi.sh install` to fix the problem.
