### ISSUE TITLE
Relay crashed when testing with several mobile clients

### ISSUE THREAD

**Issue by italod** [dedis/prifi#188]
Scenario:  Running PriFi in two Android smartphones that are exchanging messages with Telegram over PriFi.  Relay and trustee in the same server.  

Description: It was working properly for some time and then it crashed (maybe when trying to send an image over Telegram) with the following error in the relay:

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7cee28]

>goroutine 6 [running]:
github.com/lbarman/prifi/stream-multiplexer.StartEgressHandler(0xc4200234e0, 0xe, 0x1388, 0xc42009e9c0, 0xc42009ea20, 0xc420085420)
        /home/prifi/go/src/github.com/lbarman/prifi/stream-multiplexer/egress.go:57 +0x2e8
created by github.com/lbarman/prifi/sda/services.(*ServiceState).StartRelay
        /home/prifi/go/src/github.com/lbarman/prifi/sda/services/service.go:161 +0x4bd
exit status 2

**Comment by lbarman** [comment]
Working on it. I think it is fixed in `dcnet-rewrite`
