### ISSUE TITLE
Doesn't build anymore due to cli.v1

### ISSUE THREAD

**Issue by lbarman** [dedis/prifi#213]
```
[warning] using pre-created identities. Set "try_use_real_identities" to True in real deployements.
../../go/src/gopkg.in/urfave/cli.v1/docs.go:11:2: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
	/usr/local/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
	/Users/barman/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
```
```
grep -R "cli.v1" .
./sda/app/prifi.go:	"gopkg.in/urfave/cli.v1"
```

**Comment by nkcr** [comment]
Working fine with me. Maybe re-launch a `go get github.com/dedis/prifi/sda/app` ?

**Comment by tharvik** [comment]
https://github.com/urfave/cli/issues/901

**Comment by coilysiren** [comment]
I'm investigating this over in https://github.com/urfave/cli/issues/901, if anyone has any more information about this issue they should check in there!

**Comment by coilysiren** [comment]
latest information here is:

> @lynncyrin dedis/prifi#213 is resolved (or rather, not reproducable), looks like a transient issue.

=> via https://github.com/urfave/cli/issues/901#issuecomment-539883003
