### ISSUE TITLE
Error in trustee when two trustees and three clients are connected

### ISSUE THREAD

**Issue by Pamoi** [dedis/prifi#96]
On the connection of a third client with two trustees one trustee (probably the first to verify the transcript) fails with this error:

`ReceivedMessage: got an error, Could not do ReceivedTranscriptFromRelay, error is Could not locate our own permutation in the transcript...`

To reproduce you can use the default identities and run:

```
./prifi.sh relay
./prifi.sh trustee 0
./prifi.sh trustee 1
./prifi.sh client 0
./prifi.sh client 1
./prifi.sh client 2
```

**Comment by Pamoi** [comment]
When commenting out the failing checks an other issue appears when working with 3 trustees: there is a panic caused by an index out of range on line 323 of `trustee.go`:

```v := a[i*p.trusteeState.nTrustees+j][0]```

There might be a problem with the computation of this index.

**Comment by lbarman** [comment]
Fixed https://github.com/lbarman/prifi/commit/f3771d37e35b0add56c5ba5dccc2e3f9dc6b3094
