### ISSUE TITLE
Relay "out of memory exception" 

### ISSUE THREAD

**Issue by lbarman** [dedis/prifi#99]
We got this error, `go out of memory exception` while doing the demo1 @lbarman.ch. We need to investigate. 

[relay.outofmem.txt](https://github.com/lbarman/prifi/files/706912/relay.outofmem.txt)
[socks.outofmem.txt](https://github.com/lbarman/prifi/files/706911/socks.outofmem.txt)
[trustee0.outofmem.txt](https://github.com/lbarman/prifi/files/706910/trustee0.outofmem.txt)

**Comment by nikkolasg** [comment]
There has been many changes since the sda version you use. The latest onet v1 should not have any out of memory exception errors, at least from the onet part.

**Comment by lbarman** [comment]
Switched to ONet, now check that the bug is solved

**Comment by lbarman** [comment]
To be re-opened if the bug reappears.
